services:
  mysql:
    image: 'mysql:8.0'
    working_dir: /application
    volumes:
      - '.:/application'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
    ports:
      - '3306:3306'
    networks:
      - app-network
      
  vue:
    build:
      context: ./vuetify-project
    container_name: vue-app
    ports:
      - "3000:8080"
    volumes:
      - ./vuetify-project:/app
    networks:
      - app-network

  web:
    image: urnau/app1-php:prod-nginx-php-fpm8.2.3
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    volumes:
      - ./app:/var/www/app
    ports:
      - "80:80" #http
      - "443:443" #https
    networks:
      - app-network
    depends_on:
      - mysql 

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
